Repository KTwizviz/wizviz, pull requests merged in 2024-12, with the labels that each got.

#2 📌 [WV-1] setting : 프로젝트 초기 세팅
  .eslintrc.json
  .github/pullrequest.md
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  README.md
  app/favicon.ico
  app/fonts/GeistMonoVF.woff
  app/fonts/GeistVF.woff
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components.json
  components/ui/breadcrumb.tsx
  components/ui/button.tsx
  components/ui/calendar.tsx
  components/ui/card.tsx
  components/ui/carousel.tsx
  components/ui/chart.tsx
  components/ui/dialog.tsx
  components/ui/index.ts
  components/ui/input.tsx
  components/ui/pagination.tsx
  components/ui/select.tsx
  components/ui/tabs.tsx
  lib/utils.ts
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  stories/Button.stories.ts
  stories/Button.tsx
  stories/Configure.mdx
  stories/Header.stories.ts
  stories/Header.tsx
  stories/Page.stories.ts
  stories/Page.tsx
  stories/assets/accessibility.png
  stories/assets/accessibility.svg
  stories/assets/addon-library.png
  stories/assets/assets.png
  stories/assets/avif-test-image.avif
  stories/assets/context.png
  stories/assets/discord.svg
  stories/assets/docs.png
  stories/assets/figma-plugin.png
  stories/assets/github.svg
  stories/assets/share.png
  stories/assets/styling.png
  stories/assets/testing.png
  stories/assets/theming.png
  stories/assets/tutorials.svg
  stories/assets/youtube.svg
  stories/button.css
  stories/header.css
  stories/page.css
  tailwind.config.ts
  tsconfig.json
Labels: setting

#5 📌 WV-4 setting : PR build script 추가
  .github/pull_request_template.md
  .github/workflows/nextjs.yml
  components/ui/calendar.tsx
  components/ui/chart.tsx
Labels: fix, setting

#6 📌 [WV-8] setting : color design-system 설정
  app/globals.css
  app/layout.tsx
  css/color.ts
  css/globals.css
  css/index.css
  css/tailwind.css
  tailwind.config.ts
Labels: design, setting

#3 📌 [WV-5] setting : 폰트 크기 세팅
  css/font.ts
  tailwind.config.ts
Labels: design, setting

#7 💄 [WV-10] design : icon, image 추가
  assets/icons/icon_facebook.png
  assets/icons/icon_instagram.png
  assets/icons/icon_naver.png
  assets/icons/icon_ticket.png
  assets/icons/icon_user.png
  assets/icons/icon_youtube.png
  assets/images/logo_ktsports.png
  assets/images/logo_ktwiz_en.svg
  assets/images/logo_ktwiz_kr.svg
  assets/images/main_title_gallery.png
  assets/images/main_title_schedule.png
  assets/images/main_title_video.png
  assets/images/map_img.png
  assets/images/player_EomSangBaek.jpg
  assets/images/submenu_bg.png
  assets/images/team_about_img1.png
  assets/images/team_about_img2.png
  assets/images/team_about_img3.png
  assets/images/team_about_img4.png
  assets/images/wiz_park.jpg
Labels: design

#8 Dev -> Main 합병
  .github/pull_request_template.md
  .github/workflows/nextjs.yml
  app/globals.css
  app/layout.tsx
  assets/icons/icon_facebook.png
  assets/icons/icon_instagram.png
  assets/icons/icon_naver.png
  assets/icons/icon_ticket.png
  assets/icons/icon_user.png
  assets/icons/icon_youtube.png
  assets/images/logo_ktsports.png
  assets/images/logo_ktwiz_en.svg
  assets/images/logo_ktwiz_kr.svg
  assets/images/main_title_gallery.png
  assets/images/main_title_schedule.png
  assets/images/main_title_video.png
  assets/images/map_img.png
  assets/images/player_EomSangBaek.jpg
  assets/images/submenu_bg.png
  assets/images/team_about_img1.png
  assets/images/team_about_img2.png
  assets/images/team_about_img3.png
  assets/images/team_about_img4.png
  assets/images/wiz_park.jpg
  components/ui/calendar.tsx
  components/ui/chart.tsx
  css/color.ts
  css/font.ts
  css/globals.css
  css/index.css
  css/tailwind.css
  tailwind.config.ts
Labels: design, setting

#9 📌 [WV-11] : test page 생성 및 layout 구조 & 폴더 구조 설정
  app/(menu)/game/page.tsx
  app/(menu)/kt-wiz/page.tsx
  app/(menu)/layout.tsx
  app/(menu)/media/page.tsx
  app/(menu)/player/page.tsx
  app/(menu)/shop/page.tsx
  app/(menu)/sponser/page.tsx
  app/(menu)/wiz-park/page.tsx
  app/layout.tsx
  app/test/page.tsx
  public/favicon.ico
  public/fonts/GeistMonoVF.woff
  public/fonts/GeistVF.woff
  public/fonts/page.tsx
Labels: setting

#11 ➕ [WV-15] header UI 1차 생성 & favicon 설정
  app/layout.tsx
  components/layout/header.tsx
  components/layout/type.d.ts
  constants/header-menu.ts
  public/favicon.ico
  public/logo_ktwiz_kr.svg
Labels: design

#10 [WV-12] : 배너 컴포넌트 구현
  app/test/page.tsx
  components/common/sub-banner-menu/SubMenuBanner.tsx
  constants/menu-data.ts
Labels: feat, design

#12 ➕ WV-16 feat : 콘텐츠 영역 레이아웃 컴포넌트 구현
  app/(menu)/layout.tsx
  app/test/page.tsx
Labels: feat

#13 ➕ [WV-13] feat : footer를 위한 icon button, footer dialog 생성 및 적용
  app/layout.tsx
  app/page.tsx
  app/test-page/page.tsx
  assets/images/image_defeat.png
  assets/images/image_draw.png
  assets/images/image_win.png
  components/layout/footer.tsx
  components/ui/footer-dialog.tsx
  components/ui/icon-button.tsx
  components/ui/types.d.ts
  constants/footer.ts
Labels: feat, refactor

#14 🔧 [WV-12] fix: next/Image 경고 수정
  app/(menu)/layout.tsx
  components/common/sub-menu-banner/SubMenuBanner.tsx
Labels: fix

#16 ➕ [WV-15] feat : header ui 추가 생성 및 전체 폴더구조 변경
  app/(menu)/game/[...schedule]/page.tsx
  app/(menu)/ktwiz/about/page.tsx
  app/(menu)/ktwiz/bi/page.tsx
  app/(menu)/ktwiz/policy/page.tsx
  app/(menu)/ktwiz/sponsor/page.tsx
  app/(menu)/ktwiz/wallpaper/page.tsx
  app/(menu)/layout.tsx
  app/(menu)/player/catcher/page.tsx
  app/(menu)/player/cheer/cheering/page.tsx
  app/(menu)/player/cheer/copyright/page.tsx
  app/(menu)/player/cheer/page.tsx
  app/(menu)/player/cheer/song/page.tsx
  app/(menu)/player/coach/page.tsx
  app/(menu)/player/pitcher/page.tsx
  app/(menu)/wizpark/iksan/page.tsx
  app/(menu)/wizpark/intro/page.tsx
  app/(menu)/wizpark/location/page.tsx
  app/(menu)/wizpark/parking/page.tsx
  app/layout.tsx
  app/test/page.tsx
  components/layout/header.tsx
  components/layout/headerDropMenu.tsx
  components/layout/headerRightMenu.tsx
  components/layout/type.d.ts
  constants/header-menu.ts
  constants/menu-data.ts
  public/fonts/page.tsx
  tailwind.config.ts
Labels: feat, design, refactor, remove, rename, setting

#18 Dev-> Main 배포
  app/(menu)/game/[...schedule]/page.tsx
  app/(menu)/ktwiz/about/page.tsx
  app/(menu)/ktwiz/bi/page.tsx
  app/(menu)/ktwiz/policy/page.tsx
  app/(menu)/ktwiz/sponsor/page.tsx
  app/(menu)/ktwiz/wallpaper/page.tsx
  app/(menu)/layout.tsx
  app/(menu)/media/page.tsx
  app/(menu)/player/catcher/page.tsx
  app/(menu)/player/cheer/cheering/page.tsx
  app/(menu)/player/cheer/copyright/page.tsx
  app/(menu)/player/cheer/page.tsx
  app/(menu)/player/cheer/song/page.tsx
  app/(menu)/player/coach/page.tsx
  app/(menu)/player/pitcher/page.tsx
  app/(menu)/wizpark/iksan/page.tsx
  app/(menu)/wizpark/intro/page.tsx
  app/(menu)/wizpark/location/page.tsx
  app/(menu)/wizpark/parking/page.tsx
  app/favicon.ico
  app/layout.tsx
  app/page.tsx
  app/test-page/page.tsx
  assets/images/2024_post_bg_web.png
  assets/images/image_defeat.png
  assets/images/image_draw.png
  assets/images/image_win.png
  components/common/sub-menu-banner/SubMenuBanner.tsx
  components/layout/footer.tsx
  components/layout/header.tsx
  components/layout/headerDropMenu.tsx
  components/layout/headerRightMenu.tsx
  components/layout/type.d.ts
  components/main/schedule.tsx
  components/ui/footer-dialog.tsx
  components/ui/icon-button.tsx
  components/ui/types.d.ts
  constants/footer.ts
  constants/header-menu.ts
  constants/menu-data.ts
  public/fonts/GeistMonoVF.woff
  public/fonts/GeistVF.woff
  public/logo_ktwiz_kr.svg
  tailwind.config.ts
Labels: design, fix, refactor, rename, setting

#20 ➕ [WV-18] feat : 메인페이지 스케줄 컴포넌트 추가 구현
  assets/images/logo_ktwiz.png
  assets/images/logo_lgtwins.png
  assets/images/parking_reservation.png
  assets/images/schedule_video.png
  assets/images/team_ranking.png
  components/main/schedule.tsx
  constants/schedules.ts
Labels: feat, design

#19 💄 [WV-19] design : create-intro-Page 추가
  app/(menu)/intro/page.tsx
Labels: design

#21 📌 [WV-21] setting : 폰트 세팅
  app/layout.tsx
Labels: setting

#22 ✏️ [WV-19] rename : intro Page파일의 폴더 위치 변경 및 제거
  app/(menu)/intro/page.tsx
  app/(menu)/wizpark/intro/page.tsx
Labels: remove, rename

#26 💄 [WV-24] design : news card 컴포넌트 생성
  app/(menu)/media/guest/page.tsx
  app/(menu)/media/highlight/page.tsx
  app/(menu)/media/news/page.tsx
  app/(menu)/media/story/page.tsx
  assets/icons/@index.ts
  assets/icons/icon_calendar.svg
  assets/icons/icon_views.svg
  assets/images/@index.ts
  components/media/news-card.tsx
  components/media/type.d.ts
Labels: feat, design, refactor

#25 💄 [WV-22] design : create about page추가
  app/(menu)/ktwiz/about/page.tsx
Labels: design

#15 ➕ [WV-17] feat : Breadcrumb 컴포넌트 구현
  app/(menu)/layout.tsx
  components/common/SubMenuBanner.tsx
  components/common/breadcrumb/Breadcrumb.tsx
  components/common/breadcrumb/BreadcrumbSegment.tsx
  components/ui/breadcrumb.tsx
Labels: feat

#27 ➕ [WV-18] feat : main page에 gallery 추가 구현
  app/page.tsx
  assets/images/@index.ts
  assets/images/gallery1.jpeg
  assets/images/gallery10.jpeg
  assets/images/gallery2.jpeg
  assets/images/gallery3.jpeg
  assets/images/gallery4.jpeg
  assets/images/gallery5.jpeg
  assets/images/gallery6.jpeg
  assets/images/gallery7.jpeg
  assets/images/gallery8.jpeg
  assets/images/gallery9.jpeg
  assets/images/logo_ktwiz.png
  assets/images/logo_lgtwins.png
  assets/images/player_banner.png
  assets/images/schedule_video.png
  assets/images/store_banner.png
  components/main/gallery.tsx
  components/main/schedule.tsx
  components/main/video.tsx
  components/ui/carousel.tsx
  components/ui/custom-carousel.tsx
  components/ui/index.ts
  components/ui/types.d.ts
  constants/main.ts
Labels: feat, design, refactor, remove

#28 Dev -> Main 배포
  app/(menu)/ktwiz/about/page.tsx
  app/(menu)/layout.tsx
  app/(menu)/media/guest/page.tsx
  app/(menu)/media/highlight/page.tsx
  app/(menu)/media/news/page.tsx
  app/(menu)/media/story/page.tsx
  app/(menu)/wizpark/intro/page.tsx
  app/(menu)/wizpark/location/page.tsx
  app/layout.tsx
  app/page.tsx
  assets/icons/@index.ts
  assets/icons/icon_calendar.svg
  assets/icons/icon_views.svg
  assets/images/@index.ts
  assets/images/gallery1.jpeg
  assets/images/gallery10.jpeg
  assets/images/gallery2.jpeg
  assets/images/gallery3.jpeg
  assets/images/gallery4.jpeg
  assets/images/gallery5.jpeg
  assets/images/gallery6.jpeg
  assets/images/gallery7.jpeg
  assets/images/gallery8.jpeg
  assets/images/gallery9.jpeg
  assets/images/logo_HH.png
  assets/images/logo_HT.png
  assets/images/logo_KT.png
  assets/images/logo_LG.png
  assets/images/logo_LT.png
  assets/images/logo_NC.png
  assets/images/logo_OB.png
  assets/images/logo_SK.png
  assets/images/logo_SS.png
  assets/images/logo_WO.png
  assets/images/parking_reservation.png
  assets/images/player_banner.png
  assets/images/store_banner.png
  assets/images/team_ranking.png
  components/common/SubMenuBanner.tsx
  components/common/breadcrumb/Breadcrumb.tsx
  components/common/breadcrumb/BreadcrumbSegment.tsx
  components/main/gallery.tsx
  components/main/schedule.tsx
  components/main/video-card.tsx
  components/main/video.tsx
  components/media/news-card.tsx
  components/media/type.d.ts
  components/ui/breadcrumb.tsx
  components/ui/carousel.tsx
  components/ui/custom-carousel.tsx
  components/ui/index.ts
  components/ui/types.d.ts
  components/wizpark/location/Map.tsx
  constants/main.ts
  constants/wizpark-location.ts
Labels: feat, design, fix, refactor, remove

#29 💄 [WV-24] design : news page (pagination & select 추가)
  app/(menu)/media/news/page.tsx
  components/media/news-card.tsx
  components/ui/custom-pagination.tsx
  components/ui/custom-select.tsx
  constants/news-data.ts
Labels: design

#30 ♻️ [WV-15] refactor : header url 로 경로 이동 기능 수정 및 폴더구조 수정
  app/(menu)/game/[league]/boxscore/page.tsx
  app/(menu)/game/[league]/schedule/page.tsx
  app/(menu)/player/hitter/catcher/page.tsx
  app/(menu)/player/hitter/infielder/page.tsx
  app/(menu)/player/hitter/outfielder/page.tsx
  components/common/SubMenuBanner.tsx
  components/layout/header.tsx
  components/layout/headerDropMenu.tsx
  components/layout/type.d.ts
  constants/header-menu.ts
  constants/menu-data.ts
  tailwind.config.ts
Labels: feat, refactor, rename

#31 Dev -> Main 합병
  app/(menu)/game/[league]/boxscore/page.tsx
  app/(menu)/game/[league]/schedule/page.tsx
  app/(menu)/media/news/page.tsx
  app/(menu)/player/hitter/catcher/page.tsx
  app/(menu)/player/hitter/infielder/page.tsx
  app/(menu)/player/hitter/outfielder/page.tsx
  components/common/SubMenuBanner.tsx
  components/layout/header.tsx
  components/layout/headerDropMenu.tsx
  components/layout/type.d.ts
  components/media/news-card.tsx
  components/ui/custom-pagination.tsx
  components/ui/custom-select.tsx
  constants/header-menu.ts
  constants/menu-data.ts
  constants/news-data.ts
  tailwind.config.ts
Labels: feat, fix, refactor, remove, rename
