Repository KTwizviz/wizviz, pull requests merged in 2025-01, with the labels that each got.

#33 ♻️ [WV-32] refactor : subBanner (category) 쪽 1차 수정
  app/(menu)/game/[league]/ranking/page.tsx
  app/(menu)/game/[league]/watchpoint/page.tsx
  app/(menu)/layout.tsx
  app/(menu)/media/news/page.tsx
  components/common/CategoryMenu.tsx
  components/common/SubMenuBanner.tsx
  components/common/custom-pagination.tsx
  components/common/custom-select.tsx
  components/layout/headerDropMenu.tsx
  components/layout/type.d.ts
  constants/header-menu.ts
Labels: fix, refactor, remove, rename

#35 💄[WV-33] design : create-policy-page 추가
  app/(menu)/ktwiz/policy/page.tsx
  assets/images/@index.ts
  assets/images/policy_img.jpg
Labels: design

#32 💄 [WV-23] design : create parking page추가
  app/(menu)/wizpark/parking/page.tsx
  assets/icons/@index.ts
  assets/icons/icon_parking.png
  assets/images/@index.ts
  assets/images/parking_img.png
  components/wizpark/parking/parking-content.tsx
  components/wizpark/parking/parking-instructions.tsx
  components/wizpark/parking/parking-notice.tsx
  css/color.ts
  next.config.mjs
Labels: design

#37 ➕ [WV-25] feat : 스케줄 페이지 구현
  api/game/apis.ts
  app/(menu)/game/[league]/schedule/page.tsx
  app/(menu)/layout.tsx
  components/common/breadcrumb/breadcrumb-segment.tsx
  components/common/breadcrumb/breadcrumb.tsx
  components/game/schedule/all-league-cell.tsx
  components/game/schedule/calendar-cell.tsx
  components/game/schedule/ktwiz-cell.tsx
  components/game/schedule/league-schedule.tsx
  components/game/schedule/schedule-calendar.tsx
  components/game/schedule/schedule-carousel.tsx
  components/game/schedule/type.d.ts
  components/ui/custom-carousel.tsx
  components/ui/switch.tsx
  components/ui/types.d.ts
  css/color.ts
  package-lock.json
  package.json
Labels: feat, design, refactor, rename

#36 ♻️ [WV-32] refactor : subBanner(category) 최종 수정
  components/common/CategoryMenu.tsx
  components/common/type.d.ts
  constants/header-menu.ts
  utils/find-menu.ts
  utils/types.ts
Labels: feat, refactor, rename

#38 ➕ [WV-35] : feat player coach page 생성
  api/player/apis.ts
  api/player/types.ts
  app/(menu)/player/coach/[id]/page.tsx
  app/(menu)/player/coach/page.tsx
  components/layout/header.tsx
  components/layout/headerRightMenu.tsx
  components/player/coach-card.tsx
  components/player/coach-detail.tsx
  components/player/coach-list.tsx
  components/player/type.d.ts
  css/font.ts
Labels: feat, design, rename

#39 ➕ [WV-38] feat : 익산 경기장 페이지 구현
  app/(menu)/wizpark/iksan/page.tsx
  app/(menu)/wizpark/location/page.tsx
  assets/images/@index.ts
  assets/images/iksan_stadium1.jpeg
  assets/images/iksan_stadium2.jpeg
  assets/images/iksan_stadium3.png
  assets/images/iksan_stadium4.png
  assets/images/iksan_stadium5.png
  assets/images/iksan_stadium6.png
  assets/images/iksan_stadium7.png
  assets/images/iksan_stadium8.png
  assets/images/iksan_stadium9.png
  components/common/Map.tsx
  components/wizpark/iksan/bus-route-info.tsx
  components/wizpark/iksan/type.d.ts
  constants/stadium.ts
  constants/wizpark-location.ts
Labels: feat, design, rename

#41 💄 [WV-36] design : 배너 디자인 개선
  components/common/CategoryMenu.tsx
  css/color.ts
Labels: design

#42 💄[WV-39] design : create-sponsor-page 추가
  app/(menu)/ktwiz/sponsor/page.tsx
  assets/images/@index.ts
  assets/images/sponsor_bccard.gif
  assets/images/sponsor_daishin.png
  assets/images/sponsor_dongsuh.png
  assets/images/sponsor_dorco.png
  assets/images/sponsor_ktestate.jpg
  assets/images/sponsor_newbalance.png
  assets/images/sponsor_nongshim.jpg
  assets/images/sponsor_oksavingsbank.jpg
  assets/images/sponsor_onface.jpg
  assets/images/sponsor_panasonic.jpg
  assets/images/sponsor_samsung.jpg
  assets/images/sponsor_sangsangin.jpg
  assets/images/sponsor_suwon.jpg
  assets/images/sponsor_ticketlink.gif
  assets/images/sponsor_tirebank.png
  assets/images/sponsor_usana.png
  components/ktwiz/sponsor/sponsor-item.tsx
Labels: design

#40 ➕ [WV-29] feat : boxscore 페이지 생성
  api/game/api.ts
  app/(menu)/game/[league]/boxscore/page.tsx
  assets/images/@index.ts
  assets/images/gallery1.jpeg
  assets/images/gallery10.jpeg
  assets/images/gallery2.jpeg
  assets/images/gallery3.jpeg
  assets/images/gallery4.jpeg
  assets/images/gallery5.jpeg
  assets/images/gallery6.jpeg
  assets/images/gallery7.jpeg
  assets/images/gallery8.jpeg
  assets/images/gallery9.jpeg
  assets/images/logo_SSG.png
  assets/images/photos01.jpg
  assets/images/photos02.jpg
  assets/images/photos03.jpg
  assets/images/photos04.jpg
  assets/images/photos05.jpg
  assets/images/photos06.jpg
  assets/images/photos07.jpg
  assets/images/photos08.jpg
  assets/images/photos09.jpg
  assets/images/photos10.jpg
  components/common/CategoryMenu.tsx
  components/game/boxscore/area-title.tsx
  components/game/boxscore/batter-record.tsx
  components/game/boxscore/boxscore-container.tsx
  components/game/boxscore/boxscore-info.tsx
  components/game/boxscore/main-record.tsx
  components/game/boxscore/pitcher-record.tsx
  components/game/boxscore/score-board.tsx
  components/game/boxscore/team-score.tsx
  components/game/boxscore/types.d.ts
  components/ui/custom-carousel.tsx
  components/ui/icon-button.tsx
  components/ui/types.d.ts
  constants/team-logos.ts
  css/color.ts
  utils/date.ts
Labels: feat, design, fix, refactor

#43 ➕ [WV-35] feat : player - 투수 리스트 페이지 생성
  api/player/apis.ts
  api/player/types.ts
  app/(menu)/player/pitcher/page.tsx
  components/player/coach-detail.tsx
  components/player/coach-list.tsx
  components/player/pitcher-list.tsx
  components/player/player-card.tsx
  components/player/type.d.ts
Labels: feat, design, rename

#44 ♻️ [WV-29] rafactor : scoreboard css 수정
  components/game/boxscore/boxscore-info.tsx
  components/game/boxscore/score-board.tsx
  components/game/boxscore/team-score.tsx
Labels: design

#46 ♻️ [WV-40] feat : tanstack query (react query) 기본 세팅
  api/game/api.ts
  api/game/apis.ts
  app/layout.tsx
  components/game/boxscore/boxscore-container.tsx
  constants/query-keys.ts
  hooks/useBoxscore.ts
  package-lock.json
  package.json
  providers/query-provider.tsx
Labels: feat, setting

#45 ♻️ [WV-35] refactor : player coach detail 페이지 생성
  api/player/apis.ts
  api/player/types.ts
  app/(menu)/player/coach/[id]/page.tsx
  app/(menu)/player/coach/[pcode]/page.tsx
  app/(menu)/player/coach/page.tsx
  app/(menu)/player/pitcher/[pcode]/page.tsx
  app/(menu)/player/pitcher/page.tsx
  components/player/coach-detail.tsx
  components/player/coach-list.tsx
  components/player/pitcher-list.tsx
  components/player/player-card.tsx
  components/player/type.d.ts
  next.config.mjs
Labels: feat, design, refactor, rename

#49 ➕ [WV-45] feat : news detail page 생성
  api/news/apis.ts
  api/news/types.ts
  app/(menu)/media/news/[artcSeq]/page.tsx
  components/media/news-detail.tsx
  components/media/type.d.ts
Labels: feat, design

#48 ➕ [WV-42] feat : pitcher detail page 생성
  api/player/apis.ts
  api/player/types.ts
  app/(menu)/player/coach/[pcode]/page.tsx
  app/(menu)/player/coach/page.tsx
  app/(menu)/player/pitcher/[pcode]/page.tsx
  app/(menu)/player/pitcher/page.tsx
  components/player/coach/coach-detail.tsx
  components/player/coach/coach-list.tsx
  components/player/pitcher/pitcher-detail.tsx
  components/player/pitcher/pitcher-history.tsx
  components/player/pitcher/pitcher-list.tsx
  components/player/pitcher/pitcher-profile-image.tsx
  components/player/pitcher/pitcher-stats-info.tsx
  components/player/player-card.tsx
  components/player/type.d.ts
Labels: feat, design, refactor, rename

#50 🔧 [WV-37] fix : 카카오맵 로드 문제 해결
  app/(menu)/wizpark/iksan/page.tsx
  app/(menu)/wizpark/location/page.tsx
  app/layout.tsx
Labels: fix

#52 🔧 [WV-46] fix : Mixed Content Error 해결
  api/game/apis.ts
  api/player/apis.ts
  next.config.mjs
Labels: fix, setting

#54 🔧 [WV-46] fix : 머지된 API 엔드포인트 수정
  api/news/apis.ts
  api/player/apis.ts
Labels: fix

#51 💄[WV-43] design : create-wallpaper-page 추가
  app/(menu)/ktwiz/wallpaper/page.tsx
  assets/images/@index.ts
  assets/images/wallpaper_img.png
Labels: design

#53 ➕ [WV-40] refactor : main page refactor
  api/game/apis.ts
  api/main/apis.ts
  assets/images/@index.ts
  assets/images/parking_banner.png
  assets/images/parking_reservation.png
  assets/images/ranking_score.png
  assets/images/team_ranking.png
  components/game/boxscore/boxscore-container.tsx
  components/main/gallery.tsx
  components/main/parking.tsx
  components/main/schedule.tsx
  components/main/team-rank.tsx
  components/main/types.d.ts
  components/main/video.tsx
  components/skeletons/rank-skeleton.tsx
  components/skeletons/schedule-skeleton.tsx
  constants/main.ts
  hooks/useBoxscore.ts
Labels: feat, design, refactor, remove

#55 🔧 [WV-46] fix : useEffect 의존성 경고 해결
  components/common/Map.tsx
Labels: fix

#58 ♻️ [WV-42] refactor : api 수정
  api/news/apis.ts
  api/player/apis.ts
Labels: fix

#57 💄[WV-44] design : create-bi-page 추가
  app/(menu)/ktwiz/bi/page.tsx
  assets/images/@index.ts
  assets/images/bi_Image_symbol_black.png
  assets/images/bi_Image_symbol_white.png
  assets/images/bi_Initial_symbol_black.png
  assets/images/bi_Initial_symbol_white.png
  components/ktwiz/bi/bi-items.tsx
  constants/bi-data.ts
  public/bi_Image_symbol_black.png
  public/bi_Image_symbol_white.png
  public/bi_Initial_symbol_black.png
  public/bi_Initial_symbol_white.png
Labels: design, refactor

#56 Dev -> main 배포
  api/game/apis.ts
  api/main/apis.ts
  api/news/apis.ts
  api/news/types.ts
  api/player/apis.ts
  api/player/types.ts
  app/(menu)/ktwiz/bi/page.tsx
  app/(menu)/ktwiz/wallpaper/page.tsx
  app/(menu)/media/news/[artcSeq]/page.tsx
  app/(menu)/player/coach/[pcode]/page.tsx
  app/(menu)/player/coach/page.tsx
  app/(menu)/player/pitcher/[pcode]/page.tsx
  app/(menu)/player/pitcher/page.tsx
  app/(menu)/wizpark/iksan/page.tsx
  app/(menu)/wizpark/location/page.tsx
  app/layout.tsx
  assets/images/@index.ts
  assets/images/bi_Image_symbol_black.png
  assets/images/bi_Image_symbol_white.png
  assets/images/bi_Initial_symbol_black.png
  assets/images/bi_Initial_symbol_white.png
  assets/images/parking_banner.png
  assets/images/parking_reservation.png
  assets/images/ranking_score.png
  assets/images/team_ranking.png
  assets/images/wallpaper_img.png
  components/common/Map.tsx
  components/game/boxscore/boxscore-container.tsx
  components/ktwiz/bi/bi-items.tsx
  components/main/gallery.tsx
  components/main/parking.tsx
  components/main/schedule.tsx
  components/main/team-rank.tsx
  components/main/types.d.ts
  components/main/video.tsx
  components/media/news-detail.tsx
  components/media/type.d.ts
  components/player/coach/coach-detail.tsx
  components/player/coach/coach-list.tsx
  components/player/pitcher/pitcher-detail.tsx
  components/player/pitcher/pitcher-history.tsx
  components/player/pitcher/pitcher-list.tsx
  components/player/pitcher/pitcher-profile-image.tsx
  components/player/pitcher/pitcher-stats-info.tsx
  components/player/player-card.tsx
  components/player/type.d.ts
  components/skeletons/rank-skeleton.tsx
  components/skeletons/schedule-skeleton.tsx
  constants/bi-data.ts
  constants/main.ts
  hooks/useBoxscore.ts
  next.config.mjs
  public/bi_Image_symbol_black.png
  public/bi_Image_symbol_white.png
  public/bi_Initial_symbol_black.png
  public/bi_Initial_symbol_white.png
Labels: feat, design, fix, refactor, remove, rename
